---

- name: "Delete docker plateform"
  hosts: [ "all" ]
  gather_facts: no
  vars:
    ansible_connection: local
  tasks:
    - name: "Delete containers"
      docker_container:
        name: "{{inventory_hostname}}"
        force_kill: yes
        state: absent 

- name: "Delete docker network"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Delete docker network"
      docker_network:
        name: "{{network_name}}"
        state: absent

- name: "Delete Localhost RSA Key"
  hosts: localhost
  gather_facts: no
  tasks:
    - name: "Delete public Key"
      file:
        state: absent
        path: ./id_rsa.pub
    - name: "Delete private key"
      file:
        state: absent
        path: ./id_rsa
